"""Render the browser's data-file whitelist and lightweight tool catalog."""

import json


def catalog_entry(tool_id, meta):
    return {
        "id": tool_id,
        "name": meta.get("name", tool_id),
        "color": meta.get("color", "#666666"),
        "platforms": meta.get("platforms", []),
        "updatePolicy": meta.get("updatePolicy", "release-driven"),
        "builtIn": meta.get("builtIn") is True,
        "order": meta.get("order", 999),
    }


def render_data_index(tool_ids, catalog):
    return (
        "// Auto-generated by native-host/host.py. Keep this as the single data-file index.\n"
        f"window.CHEATSHEET_FILES = {json.dumps(tool_ids, ensure_ascii=False, indent=2)};\n"
        "\n// Lightweight metadata used before the full per-tool datasets are loaded.\n"
        f"window.CHEATSHEET_TOOL_CATALOG = {json.dumps(catalog, ensure_ascii=False, indent=2)};\n"
    )
